plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
title: Rumaisa Habib
description: Contact me at 23100061 (at) lums.edu.pk
avatar: /assets/me.png
subscribe: false
location: Lahore, Pakistan
author: Rumaisa Habib
skin: midnight
social:
  name: Rumaisa Habib
  links:
    - https://linkedin.com/in/rumaisahabib
    - https://github.com/RumaisaHabib
